name: Build (Android)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build APK for Android
    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # lfs: true # no lfs for now

      - name: Cache Unity Library and Gradle
        uses: actions/cache@v3
        with:
          path: |
            Library
            ~/.gradle
          key: Library-${{ hashFiles('Packages/manifest.json', 'Packages/packages-lock.json', 'ProjectSettings/ProjectSettings.asset') }}
          restore-keys: |
            Library-

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo apt-get clean

      - name: Build Unity project (Android)
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          buildName: Pong3D
          buildsPath: build
          androidExportType: 'androidPackage'

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pong3D
          path: build/Android/*.apk
